package fr.dauphine.ja.kiefferachria.MorpionSolitaire.model;

public enum Direction {
	HORIZONTAL,VERTICAL,DIAGLEFT,DIAGRIGHT,HORIZONTAL_LEFT,HORIZONTAL_RIGHT,VERTICAL_TOP,VERTICAL_BOTTOM,DIAGLEFT_TOPLEFT,DIAGLEFT_BOTTOMRIGHT,DIAGRIGHT_TOPRIGHT,DIAGRIGHT_BOTTOMLEFT,;
	
}
